"""Build/check the complete portable manuscript without an internal archive."""
import argparse
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'paper/manuscript-complete.md'


def build():
    names = ['paper/manuscript.md', 'paper/appendix-qubit.md']
    data = [(ROOT / name).read_bytes() for name in names]
    assert all(len(part) < 8 * 1024 * 1024 for part in data)
    text = '<!-- Generated by tools/build_manuscript.py; edit the two source files instead. -->\n'
    for name, part in zip(names, data):
        text += f'<!-- {name} SHA-256 {hashlib.sha256(part).hexdigest().upper()} -->\n'
    text += '\n' + '\n\n---\n\n'.join(
        part.decode('utf-8').replace('\r\n', '\n').rstrip() for part in data) + '\n'
    return text


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = build()
    if args.check:
        assert OUT.read_bytes() == text.encode('utf-8'), 'Combined manuscript is stale'
    else:
        OUT.write_text(text, encoding='utf-8', newline='\n')
    print('PASS: complete main manuscript and Appendix A, with source hashes.')


if __name__ == '__main__':
    main()
